version: '3.7'

services:     
  mariadb:
    container_name: 7_web-mariadb
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 7_myWebCalculatorDb
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5027:3306"
      
  web:
    container_name: 7_web-app-calculator
    hostname: app
    build: 7_Calculator/
    ports:
      - "0.0.0.0:5007:5007"
