pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello jenkins'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'ls -R 7_Calculator'
                sh 'docker-compose -f ./7_Calculator/7_Calculator/7_Calculator/docker-compose.yml build'
            }
        }
		stage('Start Docker Container') {
            steps {
                sh 'docker compose up -d'
            }
        }
    }
}
